### ISSUE TITLE
Support ip address with port

### ISSUE THREAD

**Issue by bingben** [k3oni/pydash#44]
Could do this?

**Comment by aaronmailageek** [comment]
@bingben unsure if this is what you meant?

`python manage.py runserver 0.0.0.0:8000` 
would listen externally on port 8000. So if the IP Address of my instance was 10.10.103.100 I would go to the url: http://10.10.103.100:8000

If you add a DNS entry to the firewall to point to that static IP e.g. exmaple.local you could use the following url:

http://example.local:8000/

**Comment by Chouchen** [comment]
I was looking for this in the doc. « how to change the port of the server? ».

It should be in it for people who doesn't know python and/or django.

**Comment by k3oni** [comment]
@Chouchen Please visit https://github.com/k3oni/pydash/wiki/Installation-using-Django-dev-server , see last entry at the bottom.
