### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by PJanisio** [k3oni/pydash#45]
Server error I gets after passing credentials into login system of pydash.

Footprint in apache2 logs:

[wsgi:warn] [pid 28372:tid 139790316758912] mod_wsgi: Compiled for Python/2.7.8.
[wsgi:warn] [pid 28372:tid 139790316758912] mod_wsgi: Runtime using Python/2.7.9.

Error Log configured in vhosts stays empty.
Using Debian 8 wheezy.

**Comment by k3oni** [comment]
Looks like a possible issue with your apache/mod_wsgi install, i would recommend going thru the install steps again and making sure everything was done right or reinstall mod_wsgi.

**Comment by PJanisio** [comment]
Damn, you were right, just forgot about chowning:

chown -R www-data.www-data pydash

Now everything works fine.
Damn me!
Thanks.
