### ISSUE TITLE
Historical data 

### ISSUE THREAD

**Issue by PJanisio** [k3oni/pydash#46]
I See that last commit was made 3 years ago but i found this script really suitable for me. Is there chance to add historical charts like daily, weekly, monthy base? 

That will make this Little program complete for me and imho for many other users. 

Thanks upfront for replying!

**Comment by k3oni** [comment]
I don't think i will implement any new features in the current version. I had an idea a while ago about a version 2 with historical data, multiple servers support etc but i'm not sure i'll get to it anytime soon as my free time has shrunk considerably the last few years.

**Comment by PJanisio** [comment]
F**ck multiserver support ;] with logging historical data script can be named as 2.0 at least. 

I can ony assume it is not some many work to do. Saving timestamp and values to database or even a txt file but I understand your position. 
So keeping fingers crossed for your free time.
