### ISSUE TITLE
Part Memory Usage not displayed

### ISSUE THREAD

**Issue by aziz-khalapoum** [k3oni/pydash#47]
Hi,
I have a problem, the Memory Usage part is not displayed.
Thank you
![memory usage](https://user-images.githubusercontent.com/20128631/27121786-f0d88e12-50e8-11e7-8c9a-be18b74a2e28.png)

**Comment by k3oni** [comment]
Can you provide some details on your system, OS?

**Comment by aziz-khalapoum** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

**Comment by k3oni** [comment]
Seems that they removed the -o option in the new version of free, use old format. Should be fixed, if you want to update your version.

**Comment by aziz-khalapoum** [comment]
This is at what level I have to modify the file. Thank you

**Comment by k3oni** [comment]
You should be able to just run 'git pull' in the main pydash directory and restart apache after that. Change should be applied .

**Comment by aziz-khalapoum** [comment]
Great!!!! it works. I manually modify the file (I saw on the commit you just made).

thank-you for your prompt response

**Comment by aziz-khalapoum** [comment]
I have a question outside the issue. Is it possible to use it for multiple servers?

**Comment by k3oni** [comment]
See #46

**Comment by aziz-khalapoum** [comment]
OK. Thanks anyway. I fully understand your constraint on time. I hope you will be led to realize it one day.

Many thanks
