### ISSUE TITLE
Request For PyDash In Virtualized Environment

### ISSUE THREAD

**Issue by MGK01** [k3oni/pydash#53]
Hi Florian, First Thanks a Ton For This Tool. I request a extended pydash version to probe multiple Linux vm's/machines performance and display multiple machines in dashboard...Is this possible with current version. Can you please help and support on same.

OR  This tool only works for one host ??

I need a similar tool to run on a cloud to monitor multiple vm's inside a cloud and report performance in dashboard. Please suggest same.

-Thanks.

**Comment by k3oni** [comment]
I had an idea a while ago about a version 2 with historical data, multiple servers support etc but i'm not sure i'll get to it anytime soon as my free time has shrunk considerably the last few years.

Take a look at netdata: https://github.com/firehol/netdata .
